### ISSUE TITLE
Backbone + Backbone-Mediator + RequireJS resulted in View Logic short-circuiting and infinite looping

### ISSUE THREAD

**Issue by gsklee** [chalbert/Backbone-Mediator#2]
More details here:

http://stackoverflow.com/questions/12245468/backbone-requirejs-mediator-pattern-resulted-in-view-logic-short-circuiting

**Comment by john-ka-peter** [comment]
Yes we do get infinite looping

<a href="http://javascripttrainingcourses.com/JS/BackboneJS-Training" title="Backbone.JS Training in Chennai">Backbone.JS Training in Chennai</a>

**Comment by chalbert** [comment]
This plugin is now extending from `Backbone.Events` instead of using its own implementation. If this is still a problem, please reopen.
