### ISSUE TITLE
"Cannot read property '$once' of undefined in line 174" when I use subscriptions object in view

### ISSUE THREAD

**Issue by Olgagr** [chalbert/Backbone-Mediator#4]
I get this error in one of my project when I'm using subscriptions object instead Backbone.Mediator.sub method. In the view I have (CoffeeScript):

```javascript
subscriptions:
  'documents:counterChange': 'updateCounter'
```

It's an error int the unsetSubscriptions method. It's trying to invoke subscription.$once but subscription is undefined. this.subscriptions is't an object with my subscription.

**Comment by chalbert** [comment]
This plugin now extends the base `Backbone.Events`, so the implementation is quite different. If this is still an issue, please reopen and include a stacktrace.
