### ISSUE TITLE
Cannot unsubscribe from an channel that was subscribed with no context

### ISSUE THREAD

**Issue by olance** [chalbert/Backbone-Mediator#6]
When a channel is subscribed to without a context, it is registered with context behing the Mediator object:

    channels[channel].push({fn: subscription, context: context || this, once: once});

Note the ```context || this```

However, when trying to unsubscribe from a channel, if I don't give any context, it will fail and *not* unsubscribe because ```context``` is taken as given to the function and compared to what was stored (which was ```this```):

    if (subscription.fn === fn && subscription.context === context)

We should find back the ```context || this``` here, otherwise it is not possible to unsubscribe without giving a context.

I guess this won't be corrected in the main repo, given the age of the other opened issues... but I guess this report could be useful to some people wondering why they can't get a channel unsubscribed.

**Comment by chalbert** [comment]
This plugin is now extending `Backbone.Events` so this should not be a problem anymore.
